name: sprint_up_shop
description: A simple Flutter shopping app (SprintUp) — sample project for learning.
publish_to: 'none'
version: 1.0.0+1


environment:
sdk: ">=2.18.0 <4.0.0"


dependencies:
flutter:
sdk: flutter
cupertino_icons: ^1.0.2
provider: ^6.0.5
cached_network_image: ^3.2.3
shared_preferences: ^2.1.1


flutter:
uses-material-design: true
assets:
- assets/images/
- assets/data/


fonts:
- family: Suwannaphum
fonts:
- asset: assets/fonts/Suwannaphum-Regular.ttf